#include <bits/stdc++.h>
#define ll long long
using namespace std;
// Get-Content t.txt | .\planet_queries_1.exe
// g++ planet_queries_1.cpp -o planet_queries_1

int main() {
    ios::sync_with_stdio(0);
    cin.tie(0);
    int n, q; cin >> n >> q;
    vector<int> teles(n + 1);
    for (int i = 1; i <= n; i++) cin >> teles[i];

    vector<vector<int>> dp(32, vector<int>(n + 1));
    for (int i = 1; i <= n; i++) {
        dp[0][i] = teles[i];
    }
    for (int i = 1; i < 32; i++) {
        for (int j = 1; j <= n; j++) {
            dp[i][j] = dp[i - 1][dp[i - 1][j]];
        }
    }

    for (int i = 0; i < q; i++) {
        int x, k; cin >> x >> k;
        for (int j = 0; j < 32; j++) {
            if ((1 << j) & k) x = dp[j][x];
        }
        cout << x << '\n';
    }
}

// use binary jumping generated by dp table to answer queries
// O((n + q)logn)